// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClaimEndDeviceRequestAuthenticatedIdentifiers claim end device request authenticated identifiers
//
// swagger:model ClaimEndDeviceRequestAuthenticatedIdentifiers
type ClaimEndDeviceRequestAuthenticatedIdentifiers struct {

	// authentication code
	AuthenticationCode string `json:"authentication_code,omitempty"`

	// dev eui
	// Format: byte
	DevEui strfmt.Base64 `json:"dev_eui,omitempty"`

	// join eui
	// Format: byte
	JoinEui strfmt.Base64 `json:"join_eui,omitempty"`
}

// Validate validates this claim end device request authenticated identifiers
func (m *ClaimEndDeviceRequestAuthenticatedIdentifiers) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClaimEndDeviceRequestAuthenticatedIdentifiers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClaimEndDeviceRequestAuthenticatedIdentifiers) UnmarshalBinary(b []byte) error {
	var res ClaimEndDeviceRequestAuthenticatedIdentifiers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
