// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACCommandBeaconFreqAns m a c command beacon freq ans
//
// swagger:model MACCommandBeaconFreqAns
type MACCommandBeaconFreqAns struct {

	// frequency ack
	FrequencyAck bool `json:"frequency_ack,omitempty"`
}

// Validate validates this m a c command beacon freq ans
func (m *MACCommandBeaconFreqAns) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MACCommandBeaconFreqAns) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACCommandBeaconFreqAns) UnmarshalBinary(b []byte) error {
	var res MACCommandBeaconFreqAns
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
