// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACCommandNewChannelAns m a c command new channel ans
//
// swagger:model MACCommandNewChannelAns
type MACCommandNewChannelAns struct {

	// data rate ack
	DataRateAck bool `json:"data_rate_ack,omitempty"`

	// frequency ack
	FrequencyAck bool `json:"frequency_ack,omitempty"`
}

// Validate validates this m a c command new channel ans
func (m *MACCommandNewChannelAns) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MACCommandNewChannelAns) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACCommandNewChannelAns) UnmarshalBinary(b []byte) error {
	var res MACCommandNewChannelAns
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
