// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACCommandBeaconTimingAns m a c command beacon timing ans
//
// swagger:model MACCommandBeaconTimingAns
type MACCommandBeaconTimingAns struct {

	// channel index
	ChannelIndex int64 `json:"channel_index,omitempty"`

	// delay
	Delay int64 `json:"delay,omitempty"`
}

// Validate validates this m a c command beacon timing ans
func (m *MACCommandBeaconTimingAns) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MACCommandBeaconTimingAns) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACCommandBeaconTimingAns) UnmarshalBinary(b []byte) error {
	var res MACCommandBeaconTimingAns
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
