// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACCommandRxParamSetupAns m a c command rx param setup ans
//
// swagger:model MACCommandRxParamSetupAns
type MACCommandRxParamSetupAns struct {

	// rx1 data rate offset ack
	Rx1DataRateOffsetAck bool `json:"rx1_data_rate_offset_ack,omitempty"`

	// rx2 data rate index ack
	Rx2DataRateIndexAck bool `json:"rx2_data_rate_index_ack,omitempty"`

	// rx2 frequency ack
	Rx2FrequencyAck bool `json:"rx2_frequency_ack,omitempty"`
}

// Validate validates this m a c command rx param setup ans
func (m *MACCommandRxParamSetupAns) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MACCommandRxParamSetupAns) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACCommandRxParamSetupAns) UnmarshalBinary(b []byte) error {
	var res MACCommandRxParamSetupAns
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
