// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACStateJoinAccept m a c state join accept
//
// swagger:model MACStateJoinAccept
type MACStateJoinAccept struct {

	// Network session keys associated with the join.
	Keys *V3SessionKeys `json:"keys,omitempty"`

	// Payload of the join-accept received from Join Server.
	// Format: byte
	Payload strfmt.Base64 `json:"payload,omitempty"`

	// JoinRequest sent to Join Server.
	Request *V3JoinRequest `json:"request,omitempty"`
}

// Validate validates this m a c state join accept
func (m *MACStateJoinAccept) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeys(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequest(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MACStateJoinAccept) validateKeys(formats strfmt.Registry) error {

	if swag.IsZero(m.Keys) { // not required
		return nil
	}

	if m.Keys != nil {
		if err := m.Keys.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("keys")
			}
			return err
		}
	}

	return nil
}

func (m *MACStateJoinAccept) validateRequest(formats strfmt.Registry) error {

	if swag.IsZero(m.Request) { // not required
		return nil
	}

	if m.Request != nil {
		if err := m.Request.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("request")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MACStateJoinAccept) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACStateJoinAccept) UnmarshalBinary(b []byte) error {
	var res MACStateJoinAccept
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
