// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACCommandPingSlotChannelReq m a c command ping slot channel req
//
// swagger:model MACCommandPingSlotChannelReq
type MACCommandPingSlotChannelReq struct {

	// data rate index
	DataRateIndex V3DataRateIndex `json:"data_rate_index,omitempty"`

	// frequency
	Frequency string `json:"frequency,omitempty"`
}

// Validate validates this m a c command ping slot channel req
func (m *MACCommandPingSlotChannelReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDataRateIndex(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MACCommandPingSlotChannelReq) validateDataRateIndex(formats strfmt.Registry) error {

	if swag.IsZero(m.DataRateIndex) { // not required
		return nil
	}

	if err := m.DataRateIndex.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("data_rate_index")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MACCommandPingSlotChannelReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACCommandPingSlotChannelReq) UnmarshalBinary(b []byte) error {
	var res MACCommandPingSlotChannelReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
