// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PictureEmbedded picture embedded
//
// swagger:model PictureEmbedded
type PictureEmbedded struct {

	// Picture data. A data URI can be constructed as follows:
	// `data:<mime_type>;base64,<data>`.
	// Format: byte
	Data strfmt.Base64 `json:"data,omitempty"`

	// MIME type of the picture.
	MimeType string `json:"mime_type,omitempty"`
}

// Validate validates this picture embedded
func (m *PictureEmbedded) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PictureEmbedded) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PictureEmbedded) UnmarshalBinary(b []byte) error {
	var res PictureEmbedded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
