// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProvisionEndDevicesRequestIdentifiersFromData provision end devices request identifiers from data
//
// swagger:model ProvisionEndDevicesRequestIdentifiersFromData
type ProvisionEndDevicesRequestIdentifiersFromData struct {

	// join eui
	// Format: byte
	JoinEui strfmt.Base64 `json:"join_eui,omitempty"`
}

// Validate validates this provision end devices request identifiers from data
func (m *ProvisionEndDevicesRequestIdentifiersFromData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProvisionEndDevicesRequestIdentifiersFromData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProvisionEndDevicesRequestIdentifiersFromData) UnmarshalBinary(b []byte) error {
	var res ProvisionEndDevicesRequestIdentifiersFromData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
