// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ApplicationWebhookMessage v3 application webhook message
//
// swagger:model v3ApplicationWebhookMessage
type V3ApplicationWebhookMessage struct {

	// Path to append to the base URL.
	Path string `json:"path,omitempty"`
}

// Validate validates this v3 application webhook message
func (m *V3ApplicationWebhookMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3ApplicationWebhookMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ApplicationWebhookMessage) UnmarshalBinary(b []byte) error {
	var res V3ApplicationWebhookMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
