// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ApplicationPackage v3 application package
//
// swagger:model v3ApplicationPackage
type V3ApplicationPackage struct {

	// default f port
	DefaultfPort int64 `json:"default_f_port,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this v3 application package
func (m *V3ApplicationPackage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3ApplicationPackage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ApplicationPackage) UnmarshalBinary(b []byte) error {
	var res V3ApplicationPackage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
