// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ApplicationPubSubFormats v3 application pub sub formats
//
// swagger:model v3ApplicationPubSubFormats
type V3ApplicationPubSubFormats struct {

	// Format and description.
	Formats map[string]string `json:"formats,omitempty"`
}

// Validate validates this v3 application pub sub formats
func (m *V3ApplicationPubSubFormats) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3ApplicationPubSubFormats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ApplicationPubSubFormats) UnmarshalBinary(b []byte) error {
	var res V3ApplicationPubSubFormats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
