// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3AppSKeyResponse v3 app s key response
//
// swagger:model v3AppSKeyResponse
type V3AppSKeyResponse struct {

	// The (encrypted) Application Session Key.
	AppsKey *V3KeyEnvelope `json:"app_s_key,omitempty"`
}

// Validate validates this v3 app s key response
func (m *V3AppSKeyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppsKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3AppSKeyResponse) validateAppsKey(formats strfmt.Registry) error {

	if swag.IsZero(m.AppsKey) { // not required
		return nil
	}

	if m.AppsKey != nil {
		if err := m.AppsKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("app_s_key")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3AppSKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3AppSKeyResponse) UnmarshalBinary(b []byte) error {
	var res V3AppSKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
