// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3CryptoServicePayloadResponse v3 crypto service payload response
//
// swagger:model v3CryptoServicePayloadResponse
type V3CryptoServicePayloadResponse struct {

	// payload
	// Format: byte
	Payload strfmt.Base64 `json:"payload,omitempty"`
}

// Validate validates this v3 crypto service payload response
func (m *V3CryptoServicePayloadResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3CryptoServicePayloadResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3CryptoServicePayloadResponse) UnmarshalBinary(b []byte) error {
	var res V3CryptoServicePayloadResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
