// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ConcentratorConfigChannel v3 concentrator config channel
//
// swagger:model v3ConcentratorConfigChannel
type V3ConcentratorConfigChannel struct {

	// Frequency (Hz).
	Frequency string `json:"frequency,omitempty"`

	// radio
	Radio int64 `json:"radio,omitempty"`
}

// Validate validates this v3 concentrator config channel
func (m *V3ConcentratorConfigChannel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3ConcentratorConfigChannel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ConcentratorConfigChannel) UnmarshalBinary(b []byte) error {
	var res V3ConcentratorConfigChannel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
