// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3DownlinkQueueRequest v3 downlink queue request
//
// swagger:model v3DownlinkQueueRequest
type V3DownlinkQueueRequest struct {

	// downlinks
	Downlinks []*V3ApplicationDownlink `json:"downlinks"`

	// end device ids
	EndDeviceIds *V3EndDeviceIdentifiers `json:"end_device_ids,omitempty"`
}

// Validate validates this v3 downlink queue request
func (m *V3DownlinkQueueRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDownlinks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEndDeviceIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3DownlinkQueueRequest) validateDownlinks(formats strfmt.Registry) error {

	if swag.IsZero(m.Downlinks) { // not required
		return nil
	}

	for i := 0; i < len(m.Downlinks); i++ {
		if swag.IsZero(m.Downlinks[i]) { // not required
			continue
		}

		if m.Downlinks[i] != nil {
			if err := m.Downlinks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("downlinks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V3DownlinkQueueRequest) validateEndDeviceIds(formats strfmt.Registry) error {

	if swag.IsZero(m.EndDeviceIds) { // not required
		return nil
	}

	if m.EndDeviceIds != nil {
		if err := m.EndDeviceIds.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("end_device_ids")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3DownlinkQueueRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3DownlinkQueueRequest) UnmarshalBinary(b []byte) error {
	var res V3DownlinkQueueRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
