// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3EndDeviceTemplate v3 end device template
//
// swagger:model v3EndDeviceTemplate
type V3EndDeviceTemplate struct {

	// end device
	EndDevice *V3EndDevice `json:"end_device,omitempty"`

	// field mask
	FieldMask *ProtobufFieldMask `json:"field_mask,omitempty"`

	// mapping key
	MappingKey string `json:"mapping_key,omitempty"`
}

// Validate validates this v3 end device template
func (m *V3EndDeviceTemplate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndDevice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFieldMask(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3EndDeviceTemplate) validateEndDevice(formats strfmt.Registry) error {

	if swag.IsZero(m.EndDevice) { // not required
		return nil
	}

	if m.EndDevice != nil {
		if err := m.EndDevice.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("end_device")
			}
			return err
		}
	}

	return nil
}

func (m *V3EndDeviceTemplate) validateFieldMask(formats strfmt.Registry) error {

	if swag.IsZero(m.FieldMask) { // not required
		return nil
	}

	if m.FieldMask != nil {
		if err := m.FieldMask.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("field_mask")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3EndDeviceTemplate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3EndDeviceTemplate) UnmarshalBinary(b []byte) error {
	var res V3EndDeviceTemplate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
