// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3EndDeviceVersionIdentifiers Identifies an end device model with version information.
//
// swagger:model v3EndDeviceVersionIdentifiers
type V3EndDeviceVersionIdentifiers struct {

	// brand id
	BrandID string `json:"brand_id,omitempty"`

	// firmware version
	FirmwareVersion string `json:"firmware_version,omitempty"`

	// hardware version
	HardwareVersion string `json:"hardware_version,omitempty"`

	// model id
	ModelID string `json:"model_id,omitempty"`
}

// Validate validates this v3 end device version identifiers
func (m *V3EndDeviceVersionIdentifiers) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3EndDeviceVersionIdentifiers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3EndDeviceVersionIdentifiers) UnmarshalBinary(b []byte) error {
	var res V3EndDeviceVersionIdentifiers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
