// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3EndDeviceIdentifiers v3 end device identifiers
//
// swagger:model v3EndDeviceIdentifiers
type V3EndDeviceIdentifiers struct {

	// application ids
	ApplicationIds *V3ApplicationIdentifiers `json:"application_ids,omitempty"`

	// The LoRaWAN DevAddr. JPM: removed byte format.
	DevAddr string `json:"dev_addr,omitempty"`

	// The LoRaWAN DevEUI. JPM: removed byte format.
	DevEui string `json:"dev_eui,omitempty"`

	// device id
	DeviceID string `json:"device_id,omitempty"`

	// The LoRaWAN JoinEUI (AppEUI until LoRaWAN 1.0.3 end devices). JPM: removed byte format.
	JoinEui string `json:"join_eui,omitempty"`
}

// Validate validates this v3 end device identifiers
func (m *V3EndDeviceIdentifiers) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApplicationIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3EndDeviceIdentifiers) validateApplicationIds(formats strfmt.Registry) error {

	if swag.IsZero(m.ApplicationIds) { // not required
		return nil
	}

	if m.ApplicationIds != nil {
		if err := m.ApplicationIds.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("application_ids")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3EndDeviceIdentifiers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3EndDeviceIdentifiers) UnmarshalBinary(b []byte) error {
	var res V3EndDeviceIdentifiers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
