// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3FrequencyPlanDescription v3 frequency plan description
//
// swagger:model v3FrequencyPlanDescription
type V3FrequencyPlanDescription struct {

	// Base frequency in MHz for hardware support (433, 470, 868 or 915)
	BaseFrequency int64 `json:"base_frequency,omitempty"`

	// The ID of the frequency that the current frequency plan is based on.
	BaseID string `json:"base_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this v3 frequency plan description
func (m *V3FrequencyPlanDescription) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3FrequencyPlanDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3FrequencyPlanDescription) UnmarshalBinary(b []byte) error {
	var res V3FrequencyPlanDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
