// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3GatewayDown GatewayDown contains downlink messages for the gateway.
//
// swagger:model v3GatewayDown
type V3GatewayDown struct {

	// DownlinkMessage for the gateway.
	DownlinkMessage *V3DownlinkMessage `json:"downlink_message,omitempty"`
}

// Validate validates this v3 gateway down
func (m *V3GatewayDown) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDownlinkMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3GatewayDown) validateDownlinkMessage(formats strfmt.Registry) error {

	if swag.IsZero(m.DownlinkMessage) { // not required
		return nil
	}

	if m.DownlinkMessage != nil {
		if err := m.DownlinkMessage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("downlink_message")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3GatewayDown) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3GatewayDown) UnmarshalBinary(b []byte) error {
	var res V3GatewayDown
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
