// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3GatewayRadio v3 gateway radio
//
// swagger:model v3GatewayRadio
type V3GatewayRadio struct {

	// chip type
	ChipType string `json:"chip_type,omitempty"`

	// enable
	Enable bool `json:"enable,omitempty"`

	// frequency
	Frequency string `json:"frequency,omitempty"`

	// rssi offset
	RssiOffset float32 `json:"rssi_offset,omitempty"`

	// tx configuration
	TxConfiguration *GatewayRadioTxConfiguration `json:"tx_configuration,omitempty"`
}

// Validate validates this v3 gateway radio
func (m *V3GatewayRadio) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTxConfiguration(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3GatewayRadio) validateTxConfiguration(formats strfmt.Registry) error {

	if swag.IsZero(m.TxConfiguration) { // not required
		return nil
	}

	if m.TxConfiguration != nil {
		if err := m.TxConfiguration.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tx_configuration")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3GatewayRadio) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3GatewayRadio) UnmarshalBinary(b []byte) error {
	var res V3GatewayRadio
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
