// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3GatewayIdentifiers v3 gateway identifiers
//
// swagger:model v3GatewayIdentifiers
type V3GatewayIdentifiers struct {

	// Secondary identifier, which can only be used in specific requests. JPM: removed format byte.
	Eui string `json:"eui,omitempty"`

	// gateway id
	GatewayID string `json:"gateway_id,omitempty"`
}

// Validate validates this v3 gateway identifiers
func (m *V3GatewayIdentifiers) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3GatewayIdentifiers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3GatewayIdentifiers) UnmarshalBinary(b []byte) error {
	var res V3GatewayIdentifiers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
