// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3JoinRequest v3 join request
//
// swagger:model v3JoinRequest
type V3JoinRequest struct {

	// Optional CFList.
	CfList *V3CFList `json:"cf_list,omitempty"`

	// correlation ids
	CorrelationIds []string `json:"correlation_ids"`

	// dev addr
	// Format: byte
	DevAddr strfmt.Base64 `json:"dev_addr,omitempty"`

	// downlink settings
	DownlinkSettings *V3DLSettings `json:"downlink_settings,omitempty"`

	// net id
	// Format: byte
	NetID strfmt.Base64 `json:"net_id,omitempty"`

	// payload
	Payload *Lorawanv3Message `json:"payload,omitempty"`

	// raw payload
	// Format: byte
	RawPayload strfmt.Base64 `json:"raw_payload,omitempty"`

	// rx delay
	RxDelay V3RxDelay `json:"rx_delay,omitempty"`

	// selected mac version
	SelectedMacVersion V3MACVersion `json:"selected_mac_version,omitempty"`
}

// Validate validates this v3 join request
func (m *V3JoinRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCfList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDownlinkSettings(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePayload(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRxDelay(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSelectedMacVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3JoinRequest) validateCfList(formats strfmt.Registry) error {

	if swag.IsZero(m.CfList) { // not required
		return nil
	}

	if m.CfList != nil {
		if err := m.CfList.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cf_list")
			}
			return err
		}
	}

	return nil
}

func (m *V3JoinRequest) validateDownlinkSettings(formats strfmt.Registry) error {

	if swag.IsZero(m.DownlinkSettings) { // not required
		return nil
	}

	if m.DownlinkSettings != nil {
		if err := m.DownlinkSettings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("downlink_settings")
			}
			return err
		}
	}

	return nil
}

func (m *V3JoinRequest) validatePayload(formats strfmt.Registry) error {

	if swag.IsZero(m.Payload) { // not required
		return nil
	}

	if m.Payload != nil {
		if err := m.Payload.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("payload")
			}
			return err
		}
	}

	return nil
}

func (m *V3JoinRequest) validateRxDelay(formats strfmt.Registry) error {

	if swag.IsZero(m.RxDelay) { // not required
		return nil
	}

	if err := m.RxDelay.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("rx_delay")
		}
		return err
	}

	return nil
}

func (m *V3JoinRequest) validateSelectedMacVersion(formats strfmt.Registry) error {

	if swag.IsZero(m.SelectedMacVersion) { // not required
		return nil
	}

	if err := m.SelectedMacVersion.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("selected_mac_version")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3JoinRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3JoinRequest) UnmarshalBinary(b []byte) error {
	var res V3JoinRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
