// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3JoinResponse v3 join response
//
// swagger:model v3JoinResponse
type V3JoinResponse struct {

	// correlation ids
	CorrelationIds []string `json:"correlation_ids"`

	// lifetime
	Lifetime string `json:"lifetime,omitempty"`

	// raw payload
	// Format: byte
	RawPayload strfmt.Base64 `json:"raw_payload,omitempty"`

	// session keys
	SessionKeys *V3SessionKeys `json:"session_keys,omitempty"`
}

// Validate validates this v3 join response
func (m *V3JoinResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSessionKeys(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3JoinResponse) validateSessionKeys(formats strfmt.Registry) error {

	if swag.IsZero(m.SessionKeys) { // not required
		return nil
	}

	if m.SessionKeys != nil {
		if err := m.SessionKeys.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("session_keys")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3JoinResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3JoinResponse) UnmarshalBinary(b []byte) error {
	var res V3JoinResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
