// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3JoinEUIPrefix v3 join e UI prefix
//
// swagger:model v3JoinEUIPrefix
type V3JoinEUIPrefix struct {

	// join eui
	// Format: byte
	JoinEui strfmt.Base64 `json:"join_eui,omitempty"`

	// length
	Length int64 `json:"length,omitempty"`
}

// Validate validates this v3 join e UI prefix
func (m *V3JoinEUIPrefix) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3JoinEUIPrefix) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3JoinEUIPrefix) UnmarshalBinary(b []byte) error {
	var res V3JoinEUIPrefix
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
