// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3KeyEnvelope v3 key envelope
//
// swagger:model v3KeyEnvelope
type V3KeyEnvelope struct {

	// encrypted key
	// Format: byte
	EncryptedKey strfmt.Base64 `json:"encrypted_key,omitempty"`

	// The label of the RFC 3394 key-encryption-key (KEK) that was used to encrypt the key.
	KekLabel string `json:"kek_label,omitempty"`

	// The unencrypted AES key.
	// Format: byte
	Key strfmt.Base64 `json:"key,omitempty"`
}

// Validate validates this v3 key envelope
func (m *V3KeyEnvelope) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3KeyEnvelope) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3KeyEnvelope) UnmarshalBinary(b []byte) error {
	var res V3KeyEnvelope
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
