// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ListFrequencyPlansResponse v3 list frequency plans response
//
// swagger:model v3ListFrequencyPlansResponse
type V3ListFrequencyPlansResponse struct {

	// frequency plans
	FrequencyPlans []*V3FrequencyPlanDescription `json:"frequency_plans"`
}

// Validate validates this v3 list frequency plans response
func (m *V3ListFrequencyPlansResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFrequencyPlans(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3ListFrequencyPlansResponse) validateFrequencyPlans(formats strfmt.Registry) error {

	if swag.IsZero(m.FrequencyPlans) { // not required
		return nil
	}

	for i := 0; i < len(m.FrequencyPlans); i++ {
		if swag.IsZero(m.FrequencyPlans[i]) { // not required
			continue
		}

		if m.FrequencyPlans[i] != nil {
			if err := m.FrequencyPlans[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("frequency_plans" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3ListFrequencyPlansResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ListFrequencyPlansResponse) UnmarshalBinary(b []byte) error {
	var res V3ListFrequencyPlansResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
