// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3MQTTConnectionInfo The connection information of an MQTT frontend.
//
// swagger:model v3MQTTConnectionInfo
type V3MQTTConnectionInfo struct {

	// The public listen address of the frontend.
	PublicAddress string `json:"public_address,omitempty"`

	// The public listen address of the TLS frontend.
	PublicTLSAddress string `json:"public_tls_address,omitempty"`

	// The username to be used for authentication.
	Username string `json:"username,omitempty"`
}

// Validate validates this v3 m q t t connection info
func (m *V3MQTTConnectionInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3MQTTConnectionInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3MQTTConnectionInfo) UnmarshalBinary(b []byte) error {
	var res V3MQTTConnectionInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
