// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3MHDR v3 m h d r
//
// swagger:model v3MHDR
type V3MHDR struct {

	// m type
	MType V3MType `json:"m_type,omitempty"`

	// major
	Major V3Major `json:"major,omitempty"`
}

// Validate validates this v3 m h d r
func (m *V3MHDR) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMajor(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3MHDR) validateMType(formats strfmt.Registry) error {

	if swag.IsZero(m.MType) { // not required
		return nil
	}

	if err := m.MType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("m_type")
		}
		return err
	}

	return nil
}

func (m *V3MHDR) validateMajor(formats strfmt.Registry) error {

	if swag.IsZero(m.Major) { // not required
		return nil
	}

	if err := m.Major.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("major")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3MHDR) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3MHDR) UnmarshalBinary(b []byte) error {
	var res V3MHDR
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
