// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3NwkSKeysResponse v3 nwk s keys response
//
// swagger:model v3NwkSKeysResponse
type V3NwkSKeysResponse struct {

	// The (encrypted) Forwarding Network Session Integrity Key (or Network Session Key in 1.0 compatibility mode).
	FNwksIntKey *V3KeyEnvelope `json:"f_nwk_s_int_key,omitempty"`

	// The (encrypted) Network Session Encryption Key.
	NwksEncKey *V3KeyEnvelope `json:"nwk_s_enc_key,omitempty"`

	// The (encrypted) Serving Network Session Integrity Key.
	SNwksIntKey *V3KeyEnvelope `json:"s_nwk_s_int_key,omitempty"`
}

// Validate validates this v3 nwk s keys response
func (m *V3NwkSKeysResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFNwksIntKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNwksEncKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSNwksIntKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3NwkSKeysResponse) validateFNwksIntKey(formats strfmt.Registry) error {

	if swag.IsZero(m.FNwksIntKey) { // not required
		return nil
	}

	if m.FNwksIntKey != nil {
		if err := m.FNwksIntKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("f_nwk_s_int_key")
			}
			return err
		}
	}

	return nil
}

func (m *V3NwkSKeysResponse) validateNwksEncKey(formats strfmt.Registry) error {

	if swag.IsZero(m.NwksEncKey) { // not required
		return nil
	}

	if m.NwksEncKey != nil {
		if err := m.NwksEncKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("nwk_s_enc_key")
			}
			return err
		}
	}

	return nil
}

func (m *V3NwkSKeysResponse) validateSNwksIntKey(formats strfmt.Registry) error {

	if swag.IsZero(m.SNwksIntKey) { // not required
		return nil
	}

	if m.SNwksIntKey != nil {
		if err := m.SNwksIntKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("s_nwk_s_int_key")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3NwkSKeysResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3NwkSKeysResponse) UnmarshalBinary(b []byte) error {
	var res V3NwkSKeysResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
