// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3OrganizationOrUserIdentifiers OrganizationOrUserIdentifiers contains either organization or user identifiers.
//
// swagger:model v3OrganizationOrUserIdentifiers
type V3OrganizationOrUserIdentifiers struct {

	// organization ids
	OrganizationIds *V3OrganizationIdentifiers `json:"organization_ids,omitempty"`

	// user ids
	UserIds *V3UserIdentifiers `json:"user_ids,omitempty"`
}

// Validate validates this v3 organization or user identifiers
func (m *V3OrganizationOrUserIdentifiers) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrganizationIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3OrganizationOrUserIdentifiers) validateOrganizationIds(formats strfmt.Registry) error {

	if swag.IsZero(m.OrganizationIds) { // not required
		return nil
	}

	if m.OrganizationIds != nil {
		if err := m.OrganizationIds.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("organization_ids")
			}
			return err
		}
	}

	return nil
}

func (m *V3OrganizationOrUserIdentifiers) validateUserIds(formats strfmt.Registry) error {

	if swag.IsZero(m.UserIds) { // not required
		return nil
	}

	if m.UserIds != nil {
		if err := m.UserIds.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user_ids")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3OrganizationOrUserIdentifiers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3OrganizationOrUserIdentifiers) UnmarshalBinary(b []byte) error {
	var res V3OrganizationOrUserIdentifiers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
