// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3OAuthClientAuthorizations v3 o auth client authorizations
//
// swagger:model v3OAuthClientAuthorizations
type V3OAuthClientAuthorizations struct {

	// authorizations
	Authorizations []*V3OAuthClientAuthorization `json:"authorizations"`
}

// Validate validates this v3 o auth client authorizations
func (m *V3OAuthClientAuthorizations) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthorizations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3OAuthClientAuthorizations) validateAuthorizations(formats strfmt.Registry) error {

	if swag.IsZero(m.Authorizations) { // not required
		return nil
	}

	for i := 0; i < len(m.Authorizations); i++ {
		if swag.IsZero(m.Authorizations[i]) { // not required
			continue
		}

		if m.Authorizations[i] != nil {
			if err := m.Authorizations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("authorizations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3OAuthClientAuthorizations) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3OAuthClientAuthorizations) UnmarshalBinary(b []byte) error {
	var res V3OAuthClientAuthorizations
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
