// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3OrganizationIdentifiers v3 organization identifiers
//
// swagger:model v3OrganizationIdentifiers
type V3OrganizationIdentifiers struct {

	// This ID shares namespace with user IDs.
	OrganizationID string `json:"organization_id,omitempty"`
}

// Validate validates this v3 organization identifiers
func (m *V3OrganizationIdentifiers) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3OrganizationIdentifiers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3OrganizationIdentifiers) UnmarshalBinary(b []byte) error {
	var res V3OrganizationIdentifiers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
