// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3QRCodeFormat v3 q r code format
//
// swagger:model v3QRCodeFormat
type V3QRCodeFormat struct {

	// description
	Description string `json:"description,omitempty"`

	// The entity fields required to generate the QR code.
	FieldMask *ProtobufFieldMask `json:"field_mask,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this v3 q r code format
func (m *V3QRCodeFormat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFieldMask(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3QRCodeFormat) validateFieldMask(formats strfmt.Registry) error {

	if swag.IsZero(m.FieldMask) { // not required
		return nil
	}

	if m.FieldMask != nil {
		if err := m.FieldMask.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("field_mask")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3QRCodeFormat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3QRCodeFormat) UnmarshalBinary(b []byte) error {
	var res V3QRCodeFormat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
