// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3SetApplicationPubSubRequest v3 set application pub sub request
//
// swagger:model v3SetApplicationPubSubRequest
type V3SetApplicationPubSubRequest struct {

	// field mask
	FieldMask *ProtobufFieldMask `json:"field_mask,omitempty"`

	// pubsub
	Pubsub *V3ApplicationPubSub `json:"pubsub,omitempty"`
}

// Validate validates this v3 set application pub sub request
func (m *V3SetApplicationPubSubRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFieldMask(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePubsub(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SetApplicationPubSubRequest) validateFieldMask(formats strfmt.Registry) error {

	if swag.IsZero(m.FieldMask) { // not required
		return nil
	}

	if m.FieldMask != nil {
		if err := m.FieldMask.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("field_mask")
			}
			return err
		}
	}

	return nil
}

func (m *V3SetApplicationPubSubRequest) validatePubsub(formats strfmt.Registry) error {

	if swag.IsZero(m.Pubsub) { // not required
		return nil
	}

	if m.Pubsub != nil {
		if err := m.Pubsub.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pubsub")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3SetApplicationPubSubRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3SetApplicationPubSubRequest) UnmarshalBinary(b []byte) error {
	var res V3SetApplicationPubSubRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
