// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3UserIdentifiers v3 user identifiers
//
// swagger:model v3UserIdentifiers
type V3UserIdentifiers struct {

	// Secondary identifier, which can only be used in specific requests.
	Email string `json:"email,omitempty"`

	// This ID shares namespace with organization IDs.
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this v3 user identifiers
func (m *V3UserIdentifiers) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3UserIdentifiers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3UserIdentifiers) UnmarshalBinary(b []byte) error {
	var res V3UserIdentifiers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
