// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3UpdateGatewayRequest v3 update gateway request
//
// swagger:model v3UpdateGatewayRequest
type V3UpdateGatewayRequest struct {

	// field mask
	FieldMask *ProtobufFieldMask `json:"field_mask,omitempty"`

	// gateway
	Gateway *V3Gateway `json:"gateway,omitempty"`
}

// Validate validates this v3 update gateway request
func (m *V3UpdateGatewayRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFieldMask(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGateway(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3UpdateGatewayRequest) validateFieldMask(formats strfmt.Registry) error {

	if swag.IsZero(m.FieldMask) { // not required
		return nil
	}

	if m.FieldMask != nil {
		if err := m.FieldMask.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("field_mask")
			}
			return err
		}
	}

	return nil
}

func (m *V3UpdateGatewayRequest) validateGateway(formats strfmt.Registry) error {

	if swag.IsZero(m.Gateway) { // not required
		return nil
	}

	if m.Gateway != nil {
		if err := m.Gateway.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gateway")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3UpdateGatewayRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3UpdateGatewayRequest) UnmarshalBinary(b []byte) error {
	var res V3UpdateGatewayRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
