// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3UpdateGatewayAPIKeyRequest v3 update gateway API key request
//
// swagger:model v3UpdateGatewayAPIKeyRequest
type V3UpdateGatewayAPIKeyRequest struct {

	// api key
	APIKey *V3APIKey `json:"api_key,omitempty"`

	// gateway ids
	GatewayIds *V3GatewayIdentifiers `json:"gateway_ids,omitempty"`
}

// Validate validates this v3 update gateway API key request
func (m *V3UpdateGatewayAPIKeyRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGatewayIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3UpdateGatewayAPIKeyRequest) validateAPIKey(formats strfmt.Registry) error {

	if swag.IsZero(m.APIKey) { // not required
		return nil
	}

	if m.APIKey != nil {
		if err := m.APIKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("api_key")
			}
			return err
		}
	}

	return nil
}

func (m *V3UpdateGatewayAPIKeyRequest) validateGatewayIds(formats strfmt.Registry) error {

	if swag.IsZero(m.GatewayIds) { // not required
		return nil
	}

	if m.GatewayIds != nil {
		if err := m.GatewayIds.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gateway_ids")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3UpdateGatewayAPIKeyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3UpdateGatewayAPIKeyRequest) UnmarshalBinary(b []byte) error {
	var res V3UpdateGatewayAPIKeyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
