// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicationPubSubNATSProvider The NATS provider settings.
//
// swagger:model ApplicationPubSubNATSProvider
type ApplicationPubSubNATSProvider struct {

	// The server connection URL.
	ServerURL string `json:"server_url,omitempty"`
}

// Validate validates this application pub sub n a t s provider
func (m *ApplicationPubSubNATSProvider) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationPubSubNATSProvider) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationPubSubNATSProvider) UnmarshalBinary(b []byte) error {
	var res ApplicationPubSubNATSProvider
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
