// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthInfoResponseAPIKeyAccess auth info response API key access
//
// swagger:model AuthInfoResponseAPIKeyAccess
type AuthInfoResponseAPIKeyAccess struct {

	// api key
	APIKey *V3APIKey `json:"api_key,omitempty"`

	// entity ids
	EntityIds *V3EntityIdentifiers `json:"entity_ids,omitempty"`
}

// Validate validates this auth info response API key access
func (m *AuthInfoResponseAPIKeyAccess) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEntityIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthInfoResponseAPIKeyAccess) validateAPIKey(formats strfmt.Registry) error {

	if swag.IsZero(m.APIKey) { // not required
		return nil
	}

	if m.APIKey != nil {
		if err := m.APIKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("api_key")
			}
			return err
		}
	}

	return nil
}

func (m *AuthInfoResponseAPIKeyAccess) validateEntityIds(formats strfmt.Registry) error {

	if swag.IsZero(m.EntityIds) { // not required
		return nil
	}

	if m.EntityIds != nil {
		if err := m.EntityIds.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("entity_ids")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuthInfoResponseAPIKeyAccess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthInfoResponseAPIKeyAccess) UnmarshalBinary(b []byte) error {
	var res AuthInfoResponseAPIKeyAccess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
