// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConcentratorConfigFSKChannel concentrator config f s k channel
//
// swagger:model ConcentratorConfigFSKChannel
type ConcentratorConfigFSKChannel struct {

	// Frequency (Hz).
	Frequency string `json:"frequency,omitempty"`

	// radio
	Radio int64 `json:"radio,omitempty"`
}

// Validate validates this concentrator config f s k channel
func (m *ConcentratorConfigFSKChannel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConcentratorConfigFSKChannel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConcentratorConfigFSKChannel) UnmarshalBinary(b []byte) error {
	var res ConcentratorConfigFSKChannel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
