// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GatewayRadioTxConfiguration gateway radio tx configuration
//
// swagger:model GatewayRadioTxConfiguration
type GatewayRadioTxConfiguration struct {

	// max frequency
	MaxFrequency string `json:"max_frequency,omitempty"`

	// min frequency
	MinFrequency string `json:"min_frequency,omitempty"`

	// notch frequency
	NotchFrequency string `json:"notch_frequency,omitempty"`
}

// Validate validates this gateway radio tx configuration
func (m *GatewayRadioTxConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GatewayRadioTxConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GatewayRadioTxConfiguration) UnmarshalBinary(b []byte) error {
	var res GatewayRadioTxConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
