// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACCommandDevStatusAns m a c command dev status ans
//
// swagger:model MACCommandDevStatusAns
type MACCommandDevStatusAns struct {

	// Device battery status.
	// 0 indicates that the device is connected to an external power source.
	// 1..254 indicates a battery level.
	// 255 indicates that the device was not able to measure the battery level.
	Battery int64 `json:"battery,omitempty"`

	// SNR of the last downlink (dB; [-32, +31]).
	Margin int32 `json:"margin,omitempty"`
}

// Validate validates this m a c command dev status ans
func (m *MACCommandDevStatusAns) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MACCommandDevStatusAns) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACCommandDevStatusAns) UnmarshalBinary(b []byte) error {
	var res MACCommandDevStatusAns
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
