// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACCommandRxParamSetupReq m a c command rx param setup req
//
// swagger:model MACCommandRxParamSetupReq
type MACCommandRxParamSetupReq struct {

	// rx1 data rate offset
	Rx1DataRateOffset int64 `json:"rx1_data_rate_offset,omitempty"`

	// rx2 data rate index
	Rx2DataRateIndex V3DataRateIndex `json:"rx2_data_rate_index,omitempty"`

	// rx2 frequency
	Rx2Frequency string `json:"rx2_frequency,omitempty"`
}

// Validate validates this m a c command rx param setup req
func (m *MACCommandRxParamSetupReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRx2DataRateIndex(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MACCommandRxParamSetupReq) validateRx2DataRateIndex(formats strfmt.Registry) error {

	if swag.IsZero(m.Rx2DataRateIndex) { // not required
		return nil
	}

	if err := m.Rx2DataRateIndex.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("rx2_data_rate_index")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MACCommandRxParamSetupReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACCommandRxParamSetupReq) UnmarshalBinary(b []byte) error {
	var res MACCommandRxParamSetupReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
