// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACCommandBeaconFreqReq m a c command beacon freq req
//
// swagger:model MACCommandBeaconFreqReq
type MACCommandBeaconFreqReq struct {

	// frequency
	Frequency string `json:"frequency,omitempty"`
}

// Validate validates this m a c command beacon freq req
func (m *MACCommandBeaconFreqReq) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MACCommandBeaconFreqReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACCommandBeaconFreqReq) UnmarshalBinary(b []byte) error {
	var res MACCommandBeaconFreqReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
