// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACCommandLinkADRReq m a c command link a d r req
//
// swagger:model MACCommandLinkADRReq
type MACCommandLinkADRReq struct {

	// channel mask
	ChannelMask []bool `json:"channel_mask"`

	// channel mask control
	ChannelMaskControl int64 `json:"channel_mask_control,omitempty"`

	// data rate index
	DataRateIndex V3DataRateIndex `json:"data_rate_index,omitempty"`

	// nb trans
	NbTrans int64 `json:"nb_trans,omitempty"`

	// tx power index
	TxPowerIndex int64 `json:"tx_power_index,omitempty"`
}

// Validate validates this m a c command link a d r req
func (m *MACCommandLinkADRReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDataRateIndex(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MACCommandLinkADRReq) validateDataRateIndex(formats strfmt.Registry) error {

	if swag.IsZero(m.DataRateIndex) { // not required
		return nil
	}

	if err := m.DataRateIndex.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("data_rate_index")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MACCommandLinkADRReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACCommandLinkADRReq) UnmarshalBinary(b []byte) error {
	var res MACCommandLinkADRReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
