// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MACCommandRekeyInd m a c command rekey ind
//
// swagger:model MACCommandRekeyInd
type MACCommandRekeyInd struct {

	// minor version
	MinorVersion V3Minor `json:"minor_version,omitempty"`
}

// Validate validates this m a c command rekey ind
func (m *MACCommandRekeyInd) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMinorVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MACCommandRekeyInd) validateMinorVersion(formats strfmt.Registry) error {

	if swag.IsZero(m.MinorVersion) { // not required
		return nil
	}

	if err := m.MinorVersion.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("minor_version")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MACCommandRekeyInd) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MACCommandRekeyInd) UnmarshalBinary(b []byte) error {
	var res MACCommandRekeyInd
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
