// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProvisionEndDevicesRequestIdentifiersList provision end devices request identifiers list
//
// swagger:model ProvisionEndDevicesRequestIdentifiersList
type ProvisionEndDevicesRequestIdentifiersList struct {

	// end device ids
	EndDeviceIds []*V3EndDeviceIdentifiers `json:"end_device_ids"`

	// join eui
	// Format: byte
	JoinEui strfmt.Base64 `json:"join_eui,omitempty"`
}

// Validate validates this provision end devices request identifiers list
func (m *ProvisionEndDevicesRequestIdentifiersList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndDeviceIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProvisionEndDevicesRequestIdentifiersList) validateEndDeviceIds(formats strfmt.Registry) error {

	if swag.IsZero(m.EndDeviceIds) { // not required
		return nil
	}

	for i := 0; i < len(m.EndDeviceIds); i++ {
		if swag.IsZero(m.EndDeviceIds[i]) { // not required
			continue
		}

		if m.EndDeviceIds[i] != nil {
			if err := m.EndDeviceIds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("end_device_ids" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProvisionEndDevicesRequestIdentifiersList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProvisionEndDevicesRequestIdentifiersList) UnmarshalBinary(b []byte) error {
	var res ProvisionEndDevicesRequestIdentifiersList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
