// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TxSettingsDownlink Transmission settings for downlink.
//
// swagger:model TxSettingsDownlink
type TxSettingsDownlink struct {

	// Index of the antenna on which the uplink was received and/or downlink must be sent.
	AntennaIndex int64 `json:"antenna_index,omitempty"`

	// Invert LoRa polarization; false for LoRaWAN uplink, true for downlink.
	InvertPolarization bool `json:"invert_polarization,omitempty"`

	// Transmission power (dBm). Only on downlink.
	TxPower float32 `json:"tx_power,omitempty"`
}

// Validate validates this tx settings downlink
func (m *TxSettingsDownlink) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TxSettingsDownlink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TxSettingsDownlink) UnmarshalBinary(b []byte) error {
	var res TxSettingsDownlink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
