// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ApplicationWebhookTemplateMessage v3 application webhook template message
//
// swagger:model v3ApplicationWebhookTemplateMessage
type V3ApplicationWebhookTemplateMessage struct {

	// Path to append to the base URL. Can contain template fields, in RFC 6570 format.
	Path string `json:"path,omitempty"`
}

// Validate validates this v3 application webhook template message
func (m *V3ApplicationWebhookTemplateMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3ApplicationWebhookTemplateMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ApplicationWebhookTemplateMessage) UnmarshalBinary(b []byte) error {
	var res V3ApplicationWebhookTemplateMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
