// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ApplicationWebhookFormats v3 application webhook formats
//
// swagger:model v3ApplicationWebhookFormats
type V3ApplicationWebhookFormats struct {

	// Format and description.
	Formats map[string]string `json:"formats,omitempty"`
}

// Validate validates this v3 application webhook formats
func (m *V3ApplicationWebhookFormats) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3ApplicationWebhookFormats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ApplicationWebhookFormats) UnmarshalBinary(b []byte) error {
	var res V3ApplicationWebhookFormats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
