// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3ApplicationWebhook v3 application webhook
//
// swagger:model v3ApplicationWebhook
type V3ApplicationWebhook struct {

	// Base URL to which the message's path is appended.
	BaseURL string `json:"base_url,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// downlink ack
	DownlinkAck *V3ApplicationWebhookMessage `json:"downlink_ack,omitempty"`

	// The API key to be used for downlink queue operations.
	// The field is provided for convenience reasons, and can contain API keys with additional rights (albeit this is discouraged).
	DownlinkAPIKey string `json:"downlink_api_key,omitempty"`

	// downlink failed
	DownlinkFailed *V3ApplicationWebhookMessage `json:"downlink_failed,omitempty"`

	// downlink nack
	DownlinkNack *V3ApplicationWebhookMessage `json:"downlink_nack,omitempty"`

	// downlink queued
	DownlinkQueued *V3ApplicationWebhookMessage `json:"downlink_queued,omitempty"`

	// downlink sent
	DownlinkSent *V3ApplicationWebhookMessage `json:"downlink_sent,omitempty"`

	// The format to use for the body.
	// Supported values depend on the Application Server configuration.
	Format string `json:"format,omitempty"`

	// HTTP headers to use.
	Headers map[string]string `json:"headers,omitempty"`

	// ids
	Ids *V3ApplicationWebhookIdentifiers `json:"ids,omitempty"`

	// join accept
	JoinAccept *V3ApplicationWebhookMessage `json:"join_accept,omitempty"`

	// location solved
	LocationSolved *V3ApplicationWebhookMessage `json:"location_solved,omitempty"`

	// The value of the fields used by the template. Maps field.id to the value.
	TemplateFields map[string]string `json:"template_fields,omitempty"`

	// The ID of the template that was used to create the Webhook.
	TemplateIds *V3ApplicationWebhookTemplateIdentifiers `json:"template_ids,omitempty"`

	// updated at
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`

	// uplink message
	UplinkMessage *V3ApplicationWebhookMessage `json:"uplink_message,omitempty"`
}

// Validate validates this v3 application webhook
func (m *V3ApplicationWebhook) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDownlinkAck(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDownlinkFailed(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDownlinkNack(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDownlinkQueued(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDownlinkSent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJoinAccept(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocationSolved(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTemplateIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUplinkMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3ApplicationWebhook) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *V3ApplicationWebhook) validateDownlinkAck(formats strfmt.Registry) error {

	if swag.IsZero(m.DownlinkAck) { // not required
		return nil
	}

	if m.DownlinkAck != nil {
		if err := m.DownlinkAck.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("downlink_ack")
			}
			return err
		}
	}

	return nil
}

func (m *V3ApplicationWebhook) validateDownlinkFailed(formats strfmt.Registry) error {

	if swag.IsZero(m.DownlinkFailed) { // not required
		return nil
	}

	if m.DownlinkFailed != nil {
		if err := m.DownlinkFailed.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("downlink_failed")
			}
			return err
		}
	}

	return nil
}

func (m *V3ApplicationWebhook) validateDownlinkNack(formats strfmt.Registry) error {

	if swag.IsZero(m.DownlinkNack) { // not required
		return nil
	}

	if m.DownlinkNack != nil {
		if err := m.DownlinkNack.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("downlink_nack")
			}
			return err
		}
	}

	return nil
}

func (m *V3ApplicationWebhook) validateDownlinkQueued(formats strfmt.Registry) error {

	if swag.IsZero(m.DownlinkQueued) { // not required
		return nil
	}

	if m.DownlinkQueued != nil {
		if err := m.DownlinkQueued.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("downlink_queued")
			}
			return err
		}
	}

	return nil
}

func (m *V3ApplicationWebhook) validateDownlinkSent(formats strfmt.Registry) error {

	if swag.IsZero(m.DownlinkSent) { // not required
		return nil
	}

	if m.DownlinkSent != nil {
		if err := m.DownlinkSent.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("downlink_sent")
			}
			return err
		}
	}

	return nil
}

func (m *V3ApplicationWebhook) validateIds(formats strfmt.Registry) error {

	if swag.IsZero(m.Ids) { // not required
		return nil
	}

	if m.Ids != nil {
		if err := m.Ids.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ids")
			}
			return err
		}
	}

	return nil
}

func (m *V3ApplicationWebhook) validateJoinAccept(formats strfmt.Registry) error {

	if swag.IsZero(m.JoinAccept) { // not required
		return nil
	}

	if m.JoinAccept != nil {
		if err := m.JoinAccept.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("join_accept")
			}
			return err
		}
	}

	return nil
}

func (m *V3ApplicationWebhook) validateLocationSolved(formats strfmt.Registry) error {

	if swag.IsZero(m.LocationSolved) { // not required
		return nil
	}

	if m.LocationSolved != nil {
		if err := m.LocationSolved.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("location_solved")
			}
			return err
		}
	}

	return nil
}

func (m *V3ApplicationWebhook) validateTemplateIds(formats strfmt.Registry) error {

	if swag.IsZero(m.TemplateIds) { // not required
		return nil
	}

	if m.TemplateIds != nil {
		if err := m.TemplateIds.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("template_ids")
			}
			return err
		}
	}

	return nil
}

func (m *V3ApplicationWebhook) validateUpdatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *V3ApplicationWebhook) validateUplinkMessage(formats strfmt.Registry) error {

	if swag.IsZero(m.UplinkMessage) { // not required
		return nil
	}

	if m.UplinkMessage != nil {
		if err := m.UplinkMessage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("uplink_message")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3ApplicationWebhook) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ApplicationWebhook) UnmarshalBinary(b []byte) error {
	var res V3ApplicationWebhook
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
