// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V3ADRAckDelayExponent v3 a d r ack delay exponent
//
// swagger:model v3ADRAckDelayExponent
type V3ADRAckDelayExponent string

const (

	// V3ADRAckDelayExponentADRACKDELAY1 captures enum value "ADR_ACK_DELAY_1"
	V3ADRAckDelayExponentADRACKDELAY1 V3ADRAckDelayExponent = "ADR_ACK_DELAY_1"

	// V3ADRAckDelayExponentADRACKDELAY2 captures enum value "ADR_ACK_DELAY_2"
	V3ADRAckDelayExponentADRACKDELAY2 V3ADRAckDelayExponent = "ADR_ACK_DELAY_2"

	// V3ADRAckDelayExponentADRACKDELAY4 captures enum value "ADR_ACK_DELAY_4"
	V3ADRAckDelayExponentADRACKDELAY4 V3ADRAckDelayExponent = "ADR_ACK_DELAY_4"

	// V3ADRAckDelayExponentADRACKDELAY8 captures enum value "ADR_ACK_DELAY_8"
	V3ADRAckDelayExponentADRACKDELAY8 V3ADRAckDelayExponent = "ADR_ACK_DELAY_8"

	// V3ADRAckDelayExponentADRACKDELAY16 captures enum value "ADR_ACK_DELAY_16"
	V3ADRAckDelayExponentADRACKDELAY16 V3ADRAckDelayExponent = "ADR_ACK_DELAY_16"

	// V3ADRAckDelayExponentADRACKDELAY32 captures enum value "ADR_ACK_DELAY_32"
	V3ADRAckDelayExponentADRACKDELAY32 V3ADRAckDelayExponent = "ADR_ACK_DELAY_32"

	// V3ADRAckDelayExponentADRACKDELAY64 captures enum value "ADR_ACK_DELAY_64"
	V3ADRAckDelayExponentADRACKDELAY64 V3ADRAckDelayExponent = "ADR_ACK_DELAY_64"

	// V3ADRAckDelayExponentADRACKDELAY128 captures enum value "ADR_ACK_DELAY_128"
	V3ADRAckDelayExponentADRACKDELAY128 V3ADRAckDelayExponent = "ADR_ACK_DELAY_128"

	// V3ADRAckDelayExponentADRACKDELAY256 captures enum value "ADR_ACK_DELAY_256"
	V3ADRAckDelayExponentADRACKDELAY256 V3ADRAckDelayExponent = "ADR_ACK_DELAY_256"

	// V3ADRAckDelayExponentADRACKDELAY512 captures enum value "ADR_ACK_DELAY_512"
	V3ADRAckDelayExponentADRACKDELAY512 V3ADRAckDelayExponent = "ADR_ACK_DELAY_512"

	// V3ADRAckDelayExponentADRACKDELAY1024 captures enum value "ADR_ACK_DELAY_1024"
	V3ADRAckDelayExponentADRACKDELAY1024 V3ADRAckDelayExponent = "ADR_ACK_DELAY_1024"

	// V3ADRAckDelayExponentADRACKDELAY2048 captures enum value "ADR_ACK_DELAY_2048"
	V3ADRAckDelayExponentADRACKDELAY2048 V3ADRAckDelayExponent = "ADR_ACK_DELAY_2048"

	// V3ADRAckDelayExponentADRACKDELAY4096 captures enum value "ADR_ACK_DELAY_4096"
	V3ADRAckDelayExponentADRACKDELAY4096 V3ADRAckDelayExponent = "ADR_ACK_DELAY_4096"

	// V3ADRAckDelayExponentADRACKDELAY8192 captures enum value "ADR_ACK_DELAY_8192"
	V3ADRAckDelayExponentADRACKDELAY8192 V3ADRAckDelayExponent = "ADR_ACK_DELAY_8192"

	// V3ADRAckDelayExponentADRACKDELAY16384 captures enum value "ADR_ACK_DELAY_16384"
	V3ADRAckDelayExponentADRACKDELAY16384 V3ADRAckDelayExponent = "ADR_ACK_DELAY_16384"

	// V3ADRAckDelayExponentADRACKDELAY32768 captures enum value "ADR_ACK_DELAY_32768"
	V3ADRAckDelayExponentADRACKDELAY32768 V3ADRAckDelayExponent = "ADR_ACK_DELAY_32768"
)

// for schema
var v3ADRAckDelayExponentEnum []interface{}

func init() {
	var res []V3ADRAckDelayExponent
	if err := json.Unmarshal([]byte(`["ADR_ACK_DELAY_1","ADR_ACK_DELAY_2","ADR_ACK_DELAY_4","ADR_ACK_DELAY_8","ADR_ACK_DELAY_16","ADR_ACK_DELAY_32","ADR_ACK_DELAY_64","ADR_ACK_DELAY_128","ADR_ACK_DELAY_256","ADR_ACK_DELAY_512","ADR_ACK_DELAY_1024","ADR_ACK_DELAY_2048","ADR_ACK_DELAY_4096","ADR_ACK_DELAY_8192","ADR_ACK_DELAY_16384","ADR_ACK_DELAY_32768"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v3ADRAckDelayExponentEnum = append(v3ADRAckDelayExponentEnum, v)
	}
}

func (m V3ADRAckDelayExponent) validateV3ADRAckDelayExponentEnum(path, location string, value V3ADRAckDelayExponent) error {
	if err := validate.Enum(path, location, value, v3ADRAckDelayExponentEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this v3 a d r ack delay exponent
func (m V3ADRAckDelayExponent) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV3ADRAckDelayExponentEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
