// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ApplicationWebhookTemplateIdentifiers v3 application webhook template identifiers
//
// swagger:model v3ApplicationWebhookTemplateIdentifiers
type V3ApplicationWebhookTemplateIdentifiers struct {

	// template id
	TemplateID string `json:"template_id,omitempty"`
}

// Validate validates this v3 application webhook template identifiers
func (m *V3ApplicationWebhookTemplateIdentifiers) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3ApplicationWebhookTemplateIdentifiers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ApplicationWebhookTemplateIdentifiers) UnmarshalBinary(b []byte) error {
	var res V3ApplicationWebhookTemplateIdentifiers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
