// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ApplicationDownlinkFailed v3 application downlink failed
//
// swagger:model v3ApplicationDownlinkFailed
type V3ApplicationDownlinkFailed struct {

	// downlink
	Downlink *V3ApplicationDownlink `json:"downlink,omitempty"`

	// error
	Error *V3ErrorDetails `json:"error,omitempty"`
}

// Validate validates this v3 application downlink failed
func (m *V3ApplicationDownlinkFailed) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDownlink(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3ApplicationDownlinkFailed) validateDownlink(formats strfmt.Registry) error {

	if swag.IsZero(m.Downlink) { // not required
		return nil
	}

	if m.Downlink != nil {
		if err := m.Downlink.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("downlink")
			}
			return err
		}
	}

	return nil
}

func (m *V3ApplicationDownlinkFailed) validateError(formats strfmt.Registry) error {

	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {
		if err := m.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3ApplicationDownlinkFailed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ApplicationDownlinkFailed) UnmarshalBinary(b []byte) error {
	var res V3ApplicationDownlinkFailed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
