// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3Collaborators v3 collaborators
//
// swagger:model v3Collaborators
type V3Collaborators struct {

	// collaborators
	Collaborators []*V3Collaborator `json:"collaborators"`
}

// Validate validates this v3 collaborators
func (m *V3Collaborators) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCollaborators(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3Collaborators) validateCollaborators(formats strfmt.Registry) error {

	if swag.IsZero(m.Collaborators) { // not required
		return nil
	}

	for i := 0; i < len(m.Collaborators); i++ {
		if swag.IsZero(m.Collaborators[i]) { // not required
			continue
		}

		if m.Collaborators[i] != nil {
			if err := m.Collaborators[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("collaborators" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3Collaborators) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3Collaborators) UnmarshalBinary(b []byte) error {
	var res V3Collaborators
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
