// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3CreateOrganizationRequest v3 create organization request
//
// swagger:model v3CreateOrganizationRequest
type V3CreateOrganizationRequest struct {

	// Collaborator to grant all rights on the newly created application.
	// NOTE: It is currently not possible to have organizations collaborating on
	// other organizations.
	Collaborator *V3OrganizationOrUserIdentifiers `json:"collaborator,omitempty"`

	// organization
	Organization *V3Organization `json:"organization,omitempty"`
}

// Validate validates this v3 create organization request
func (m *V3CreateOrganizationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCollaborator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrganization(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3CreateOrganizationRequest) validateCollaborator(formats strfmt.Registry) error {

	if swag.IsZero(m.Collaborator) { // not required
		return nil
	}

	if m.Collaborator != nil {
		if err := m.Collaborator.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("collaborator")
			}
			return err
		}
	}

	return nil
}

func (m *V3CreateOrganizationRequest) validateOrganization(formats strfmt.Registry) error {

	if swag.IsZero(m.Organization) { // not required
		return nil
	}

	if m.Organization != nil {
		if err := m.Organization.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("organization")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3CreateOrganizationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3CreateOrganizationRequest) UnmarshalBinary(b []byte) error {
	var res V3CreateOrganizationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
