// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3CreateClientRequest v3 create client request
//
// swagger:model v3CreateClientRequest
type V3CreateClientRequest struct {

	// client
	Client *V3Client `json:"client,omitempty"`

	// Collaborator to grant all rights on the newly created client.
	Collaborator *V3OrganizationOrUserIdentifiers `json:"collaborator,omitempty"`
}

// Validate validates this v3 create client request
func (m *V3CreateClientRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClient(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCollaborator(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3CreateClientRequest) validateClient(formats strfmt.Registry) error {

	if swag.IsZero(m.Client) { // not required
		return nil
	}

	if m.Client != nil {
		if err := m.Client.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("client")
			}
			return err
		}
	}

	return nil
}

func (m *V3CreateClientRequest) validateCollaborator(formats strfmt.Registry) error {

	if swag.IsZero(m.Collaborator) { // not required
		return nil
	}

	if m.Collaborator != nil {
		if err := m.Collaborator.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("collaborator")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3CreateClientRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3CreateClientRequest) UnmarshalBinary(b []byte) error {
	var res V3CreateClientRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
