// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3DownlinkMessage Downlink message from the network to the end device
//
// swagger:model v3DownlinkMessage
type V3DownlinkMessage struct {

	// correlation ids
	CorrelationIds []string `json:"correlation_ids"`

	// end device ids
	EndDeviceIds *V3EndDeviceIdentifiers `json:"end_device_ids,omitempty"`

	// payload
	Payload *Lorawanv3Message `json:"payload,omitempty"`

	// raw payload
	// Format: byte
	RawPayload strfmt.Base64 `json:"raw_payload,omitempty"`

	// request
	Request *V3TxRequest `json:"request,omitempty"`

	// scheduled
	Scheduled *V3TxSettings `json:"scheduled,omitempty"`
}

// Validate validates this v3 downlink message
func (m *V3DownlinkMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndDeviceIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePayload(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequest(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScheduled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3DownlinkMessage) validateEndDeviceIds(formats strfmt.Registry) error {

	if swag.IsZero(m.EndDeviceIds) { // not required
		return nil
	}

	if m.EndDeviceIds != nil {
		if err := m.EndDeviceIds.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("end_device_ids")
			}
			return err
		}
	}

	return nil
}

func (m *V3DownlinkMessage) validatePayload(formats strfmt.Registry) error {

	if swag.IsZero(m.Payload) { // not required
		return nil
	}

	if m.Payload != nil {
		if err := m.Payload.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("payload")
			}
			return err
		}
	}

	return nil
}

func (m *V3DownlinkMessage) validateRequest(formats strfmt.Registry) error {

	if swag.IsZero(m.Request) { // not required
		return nil
	}

	if m.Request != nil {
		if err := m.Request.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("request")
			}
			return err
		}
	}

	return nil
}

func (m *V3DownlinkMessage) validateScheduled(formats strfmt.Registry) error {

	if swag.IsZero(m.Scheduled) { // not required
		return nil
	}

	if m.Scheduled != nil {
		if err := m.Scheduled.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scheduled")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3DownlinkMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3DownlinkMessage) UnmarshalBinary(b []byte) error {
	var res V3DownlinkMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
