// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3DataRate v3 data rate
//
// swagger:model v3DataRate
type V3DataRate struct {

	// fsk
	Fsk *V3FSKDataRate `json:"fsk,omitempty"`

	// lora
	Lora *V3LoRaDataRate `json:"lora,omitempty"`
}

// Validate validates this v3 data rate
func (m *V3DataRate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFsk(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLora(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3DataRate) validateFsk(formats strfmt.Registry) error {

	if swag.IsZero(m.Fsk) { // not required
		return nil
	}

	if m.Fsk != nil {
		if err := m.Fsk.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fsk")
			}
			return err
		}
	}

	return nil
}

func (m *V3DataRate) validateLora(formats strfmt.Registry) error {

	if swag.IsZero(m.Lora) { // not required
		return nil
	}

	if m.Lora != nil {
		if err := m.Lora.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("lora")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3DataRate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3DataRate) UnmarshalBinary(b []byte) error {
	var res V3DataRate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
