// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3EndDevices v3 end devices
//
// swagger:model v3EndDevices
type V3EndDevices struct {

	// end devices
	EndDevices []*V3EndDevice `json:"end_devices"`
}

// Validate validates this v3 end devices
func (m *V3EndDevices) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndDevices(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3EndDevices) validateEndDevices(formats strfmt.Registry) error {

	if swag.IsZero(m.EndDevices) { // not required
		return nil
	}

	for i := 0; i < len(m.EndDevices); i++ {
		if swag.IsZero(m.EndDevices[i]) { // not required
			continue
		}

		if m.EndDevices[i] != nil {
			if err := m.EndDevices[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("end_devices" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3EndDevices) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3EndDevices) UnmarshalBinary(b []byte) error {
	var res V3EndDevices
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
