// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3EndDeviceTemplateFormats v3 end device template formats
//
// swagger:model v3EndDeviceTemplateFormats
type V3EndDeviceTemplateFormats struct {

	// formats
	Formats map[string]V3EndDeviceTemplateFormat `json:"formats,omitempty"`
}

// Validate validates this v3 end device template formats
func (m *V3EndDeviceTemplateFormats) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFormats(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3EndDeviceTemplateFormats) validateFormats(formats strfmt.Registry) error {

	if swag.IsZero(m.Formats) { // not required
		return nil
	}

	for k := range m.Formats {

		if err := validate.Required("formats"+"."+k, "body", m.Formats[k]); err != nil {
			return err
		}
		if val, ok := m.Formats[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3EndDeviceTemplateFormats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3EndDeviceTemplateFormats) UnmarshalBinary(b []byte) error {
	var res V3EndDeviceTemplateFormats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
