// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3FCtrl v3 f ctrl
//
// swagger:model v3FCtrl
type V3FCtrl struct {

	// ack
	Ack bool `json:"ack,omitempty"`

	// adr
	Adr bool `json:"adr,omitempty"`

	// adr ack req
	AdrAckReq bool `json:"adr_ack_req,omitempty"`

	// class b
	Classb bool `json:"class_b,omitempty"`

	// f pending
	FPending bool `json:"f_pending,omitempty"`
}

// Validate validates this v3 f ctrl
func (m *V3FCtrl) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3FCtrl) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3FCtrl) UnmarshalBinary(b []byte) error {
	var res V3FCtrl
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
