// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3FSKDataRate v3 f s k data rate
//
// swagger:model v3FSKDataRate
type V3FSKDataRate struct {

	// Bit rate (bps).
	BitRate int64 `json:"bit_rate,omitempty"`
}

// Validate validates this v3 f s k data rate
func (m *V3FSKDataRate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3FSKDataRate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3FSKDataRate) UnmarshalBinary(b []byte) error {
	var res V3FSKDataRate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
