// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3GenerateDevAddrResponse v3 generate dev addr response
//
// swagger:model v3GenerateDevAddrResponse
type V3GenerateDevAddrResponse struct {

	// dev addr
	// Format: byte
	DevAddr strfmt.Base64 `json:"dev_addr,omitempty"`
}

// Validate validates this v3 generate dev addr response
func (m *V3GenerateDevAddrResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3GenerateDevAddrResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3GenerateDevAddrResponse) UnmarshalBinary(b []byte) error {
	var res V3GenerateDevAddrResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
