// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3Gateways v3 gateways
//
// swagger:model v3Gateways
type V3Gateways struct {

	// gateways
	Gateways []*V3Gateway `json:"gateways"`
}

// Validate validates this v3 gateways
func (m *V3Gateways) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGateways(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3Gateways) validateGateways(formats strfmt.Registry) error {

	if swag.IsZero(m.Gateways) { // not required
		return nil
	}

	for i := 0; i < len(m.Gateways); i++ {
		if swag.IsZero(m.Gateways[i]) { // not required
			continue
		}

		if m.Gateways[i] != nil {
			if err := m.Gateways[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("gateways" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3Gateways) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3Gateways) UnmarshalBinary(b []byte) error {
	var res V3Gateways
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
