// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3JoinRequestPayload v3 join request payload
//
// swagger:model v3JoinRequestPayload
type V3JoinRequestPayload struct {

	// dev eui
	// Format: byte
	DevEui strfmt.Base64 `json:"dev_eui,omitempty"`

	// dev nonce
	// Format: byte
	DevNonce strfmt.Base64 `json:"dev_nonce,omitempty"`

	// join eui
	// Format: byte
	JoinEui strfmt.Base64 `json:"join_eui,omitempty"`
}

// Validate validates this v3 join request payload
func (m *V3JoinRequestPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3JoinRequestPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3JoinRequestPayload) UnmarshalBinary(b []byte) error {
	var res V3JoinRequestPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
