// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3MACParametersChannel v3 m a c parameters channel
//
// swagger:model v3MACParametersChannel
type V3MACParametersChannel struct {

	// Downlink frequency of the channel (Hz).
	DownlinkFrequency string `json:"downlink_frequency,omitempty"`

	// Channel can be used by device for uplink.
	EnableUplink bool `json:"enable_uplink,omitempty"`

	// Index of the maximum data rate for uplink.
	MaxDataRateIndex V3DataRateIndex `json:"max_data_rate_index,omitempty"`

	// Index of the minimum data rate for uplink.
	MinDataRateIndex V3DataRateIndex `json:"min_data_rate_index,omitempty"`

	// Uplink frequency of the channel (Hz).
	UplinkFrequency string `json:"uplink_frequency,omitempty"`
}

// Validate validates this v3 m a c parameters channel
func (m *V3MACParametersChannel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMaxDataRateIndex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMinDataRateIndex(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3MACParametersChannel) validateMaxDataRateIndex(formats strfmt.Registry) error {

	if swag.IsZero(m.MaxDataRateIndex) { // not required
		return nil
	}

	if err := m.MaxDataRateIndex.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("max_data_rate_index")
		}
		return err
	}

	return nil
}

func (m *V3MACParametersChannel) validateMinDataRateIndex(formats strfmt.Registry) error {

	if swag.IsZero(m.MinDataRateIndex) { // not required
		return nil
	}

	if err := m.MinDataRateIndex.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("min_data_rate_index")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3MACParametersChannel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3MACParametersChannel) UnmarshalBinary(b []byte) error {
	var res V3MACParametersChannel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
