// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V3RejoinCountExponent v3 rejoin count exponent
//
// swagger:model v3RejoinCountExponent
type V3RejoinCountExponent string

const (

	// V3RejoinCountExponentREJOINCOUNT16 captures enum value "REJOIN_COUNT_16"
	V3RejoinCountExponentREJOINCOUNT16 V3RejoinCountExponent = "REJOIN_COUNT_16"

	// V3RejoinCountExponentREJOINCOUNT32 captures enum value "REJOIN_COUNT_32"
	V3RejoinCountExponentREJOINCOUNT32 V3RejoinCountExponent = "REJOIN_COUNT_32"

	// V3RejoinCountExponentREJOINCOUNT64 captures enum value "REJOIN_COUNT_64"
	V3RejoinCountExponentREJOINCOUNT64 V3RejoinCountExponent = "REJOIN_COUNT_64"

	// V3RejoinCountExponentREJOINCOUNT128 captures enum value "REJOIN_COUNT_128"
	V3RejoinCountExponentREJOINCOUNT128 V3RejoinCountExponent = "REJOIN_COUNT_128"

	// V3RejoinCountExponentREJOINCOUNT256 captures enum value "REJOIN_COUNT_256"
	V3RejoinCountExponentREJOINCOUNT256 V3RejoinCountExponent = "REJOIN_COUNT_256"

	// V3RejoinCountExponentREJOINCOUNT512 captures enum value "REJOIN_COUNT_512"
	V3RejoinCountExponentREJOINCOUNT512 V3RejoinCountExponent = "REJOIN_COUNT_512"

	// V3RejoinCountExponentREJOINCOUNT1024 captures enum value "REJOIN_COUNT_1024"
	V3RejoinCountExponentREJOINCOUNT1024 V3RejoinCountExponent = "REJOIN_COUNT_1024"

	// V3RejoinCountExponentREJOINCOUNT2048 captures enum value "REJOIN_COUNT_2048"
	V3RejoinCountExponentREJOINCOUNT2048 V3RejoinCountExponent = "REJOIN_COUNT_2048"

	// V3RejoinCountExponentREJOINCOUNT4096 captures enum value "REJOIN_COUNT_4096"
	V3RejoinCountExponentREJOINCOUNT4096 V3RejoinCountExponent = "REJOIN_COUNT_4096"

	// V3RejoinCountExponentREJOINCOUNT8192 captures enum value "REJOIN_COUNT_8192"
	V3RejoinCountExponentREJOINCOUNT8192 V3RejoinCountExponent = "REJOIN_COUNT_8192"

	// V3RejoinCountExponentREJOINCOUNT16384 captures enum value "REJOIN_COUNT_16384"
	V3RejoinCountExponentREJOINCOUNT16384 V3RejoinCountExponent = "REJOIN_COUNT_16384"

	// V3RejoinCountExponentREJOINCOUNT32768 captures enum value "REJOIN_COUNT_32768"
	V3RejoinCountExponentREJOINCOUNT32768 V3RejoinCountExponent = "REJOIN_COUNT_32768"

	// V3RejoinCountExponentREJOINCOUNT65536 captures enum value "REJOIN_COUNT_65536"
	V3RejoinCountExponentREJOINCOUNT65536 V3RejoinCountExponent = "REJOIN_COUNT_65536"

	// V3RejoinCountExponentREJOINCOUNT131072 captures enum value "REJOIN_COUNT_131072"
	V3RejoinCountExponentREJOINCOUNT131072 V3RejoinCountExponent = "REJOIN_COUNT_131072"

	// V3RejoinCountExponentREJOINCOUNT262144 captures enum value "REJOIN_COUNT_262144"
	V3RejoinCountExponentREJOINCOUNT262144 V3RejoinCountExponent = "REJOIN_COUNT_262144"

	// V3RejoinCountExponentREJOINCOUNT524288 captures enum value "REJOIN_COUNT_524288"
	V3RejoinCountExponentREJOINCOUNT524288 V3RejoinCountExponent = "REJOIN_COUNT_524288"
)

// for schema
var v3RejoinCountExponentEnum []interface{}

func init() {
	var res []V3RejoinCountExponent
	if err := json.Unmarshal([]byte(`["REJOIN_COUNT_16","REJOIN_COUNT_32","REJOIN_COUNT_64","REJOIN_COUNT_128","REJOIN_COUNT_256","REJOIN_COUNT_512","REJOIN_COUNT_1024","REJOIN_COUNT_2048","REJOIN_COUNT_4096","REJOIN_COUNT_8192","REJOIN_COUNT_16384","REJOIN_COUNT_32768","REJOIN_COUNT_65536","REJOIN_COUNT_131072","REJOIN_COUNT_262144","REJOIN_COUNT_524288"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v3RejoinCountExponentEnum = append(v3RejoinCountExponentEnum, v)
	}
}

func (m V3RejoinCountExponent) validateV3RejoinCountExponentEnum(path, location string, value V3RejoinCountExponent) error {
	if err := validate.Enum(path, location, value, v3RejoinCountExponentEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this v3 rejoin count exponent
func (m V3RejoinCountExponent) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV3RejoinCountExponentEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
