// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3SetClientCollaboratorRequest v3 set client collaborator request
//
// swagger:model v3SetClientCollaboratorRequest
type V3SetClientCollaboratorRequest struct {

	// client ids
	ClientIds *V3ClientIdentifiers `json:"client_ids,omitempty"`

	// collaborator
	Collaborator *V3Collaborator `json:"collaborator,omitempty"`
}

// Validate validates this v3 set client collaborator request
func (m *V3SetClientCollaboratorRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCollaborator(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SetClientCollaboratorRequest) validateClientIds(formats strfmt.Registry) error {

	if swag.IsZero(m.ClientIds) { // not required
		return nil
	}

	if m.ClientIds != nil {
		if err := m.ClientIds.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("client_ids")
			}
			return err
		}
	}

	return nil
}

func (m *V3SetClientCollaboratorRequest) validateCollaborator(formats strfmt.Registry) error {

	if swag.IsZero(m.Collaborator) { // not required
		return nil
	}

	if m.Collaborator != nil {
		if err := m.Collaborator.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("collaborator")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3SetClientCollaboratorRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3SetClientCollaboratorRequest) UnmarshalBinary(b []byte) error {
	var res V3SetClientCollaboratorRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
