// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3SetApplicationPackageAssociationRequest v3 set application package association request
//
// swagger:model v3SetApplicationPackageAssociationRequest
type V3SetApplicationPackageAssociationRequest struct {

	// association
	Association *V3ApplicationPackageAssociation `json:"association,omitempty"`

	// field mask
	FieldMask *ProtobufFieldMask `json:"field_mask,omitempty"`
}

// Validate validates this v3 set application package association request
func (m *V3SetApplicationPackageAssociationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssociation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFieldMask(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SetApplicationPackageAssociationRequest) validateAssociation(formats strfmt.Registry) error {

	if swag.IsZero(m.Association) { // not required
		return nil
	}

	if m.Association != nil {
		if err := m.Association.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("association")
			}
			return err
		}
	}

	return nil
}

func (m *V3SetApplicationPackageAssociationRequest) validateFieldMask(formats strfmt.Registry) error {

	if swag.IsZero(m.FieldMask) { // not required
		return nil
	}

	if m.FieldMask != nil {
		if err := m.FieldMask.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("field_mask")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3SetApplicationPackageAssociationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3SetApplicationPackageAssociationRequest) UnmarshalBinary(b []byte) error {
	var res V3SetApplicationPackageAssociationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
