// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3SetOrganizationCollaboratorRequest v3 set organization collaborator request
//
// swagger:model v3SetOrganizationCollaboratorRequest
type V3SetOrganizationCollaboratorRequest struct {

	// collaborator
	Collaborator *V3Collaborator `json:"collaborator,omitempty"`

	// organization ids
	OrganizationIds *V3OrganizationIdentifiers `json:"organization_ids,omitempty"`
}

// Validate validates this v3 set organization collaborator request
func (m *V3SetOrganizationCollaboratorRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCollaborator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrganizationIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SetOrganizationCollaboratorRequest) validateCollaborator(formats strfmt.Registry) error {

	if swag.IsZero(m.Collaborator) { // not required
		return nil
	}

	if m.Collaborator != nil {
		if err := m.Collaborator.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("collaborator")
			}
			return err
		}
	}

	return nil
}

func (m *V3SetOrganizationCollaboratorRequest) validateOrganizationIds(formats strfmt.Registry) error {

	if swag.IsZero(m.OrganizationIds) { // not required
		return nil
	}

	if m.OrganizationIds != nil {
		if err := m.OrganizationIds.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("organization_ids")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3SetOrganizationCollaboratorRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3SetOrganizationCollaboratorRequest) UnmarshalBinary(b []byte) error {
	var res V3SetOrganizationCollaboratorRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
