// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3UpdateOrganizationRequest v3 update organization request
//
// swagger:model v3UpdateOrganizationRequest
type V3UpdateOrganizationRequest struct {

	// field mask
	FieldMask *ProtobufFieldMask `json:"field_mask,omitempty"`

	// organization
	Organization *V3Organization `json:"organization,omitempty"`
}

// Validate validates this v3 update organization request
func (m *V3UpdateOrganizationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFieldMask(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrganization(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3UpdateOrganizationRequest) validateFieldMask(formats strfmt.Registry) error {

	if swag.IsZero(m.FieldMask) { // not required
		return nil
	}

	if m.FieldMask != nil {
		if err := m.FieldMask.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("field_mask")
			}
			return err
		}
	}

	return nil
}

func (m *V3UpdateOrganizationRequest) validateOrganization(formats strfmt.Registry) error {

	if swag.IsZero(m.Organization) { // not required
		return nil
	}

	if m.Organization != nil {
		if err := m.Organization.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("organization")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3UpdateOrganizationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3UpdateOrganizationRequest) UnmarshalBinary(b []byte) error {
	var res V3UpdateOrganizationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
